api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_enabled: false
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 30
        items_per_page_parameter_name: itemsPerPage # Default value
    collection:
        pagination:
            page_parameter_name: page